apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fleets.live-streaming-server.net
spec:
  group: live-streaming-server.net
  names:
    kind: Fleet
    listKind: FleetList
    plural: fleets
    singular: fleet
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              activePods:
                format: int32
                nullable: false
                type: integer
              pendingStopPods:
                format: int32
                nullable: false
                type: integer
              totalStreams:
                format: int32
                nullable: false
                type: integer
            type: object
          spec:
            nullable: false
            properties:
              minReplicas:
                description: The minimum number of replicas.
                exclusiveMinimum: false
                format: int32
                minimum: 1.0
                nullable: false
                type: integer
              maxReplicas:
                description: The maximum number of replicas.
                exclusiveMinimum: false
                format: int32
                minimum: 1.0
                nullable: false
                type: integer
              podStreamsLimit:
                description: The maximum number of streams that a single pod can publish.
                exclusiveMinimum: false
                format: int32
                minimum: 1.0
                nullable: false
                type: integer
              targetUtilization:
                description: The target utilization rate for the pod.
                exclusiveMaximum: true
                exclusiveMinimum: false
                format: float
                maximum: 1.0
                minimum: 0.0
                nullable: false
                type: number
              syncPeriodSeconds:
                description: The time interval of resource audits to maintain the desired state across the fleet of pods.
                exclusiveMinimum: false
                format: int32
                minimum: 1.0
                nullable: false
                type: integer
              scaleUpStabilizationWindowSeconds:
                description: The stabilization window for scaling up.
                exclusiveMinimum: false
                format: int32
                minimum: 0.0
                nullable: false
                type: integer
              scaleDownStabilizationWindowSeconds:
                description: The stabilization window for scaling down.
                exclusiveMinimum: false
                format: int32
                minimum: 0.0
                nullable: false
                type: integer
              template:
                description: The pod template of live streaming server.
                nullable: false
                type: object
                x-kubernetes-embedded-resource: true
                x-kubernetes-preserve-unknown-fields: true
            required:
            - template
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}